# Generated by Django 4.2.4 on 2023-09-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("carbs", models.FloatField()),
                ("protein", models.FloatField()),
                ("fat", models.FloatField()),
                ("calories", models.IntegerField()),
            ],
        ),
    ]
